/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardSetSelector: typeof import('./src/components/CardSetSelector.vue')['default']
    DiceCell: typeof import('./src/components/DiceCell.vue')['default']
    FontSelector: typeof import('./src/components/FontSelector.vue')['default']
    GlobalSettings: typeof import('./src/components/GlobalSettings.vue')['default']
    Markdown: typeof import('./src/components/Markdown.vue')['default']
    PatternCell: typeof import('./src/components/PatternCell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SameImageCell: typeof import('./src/components/SameImageCell.vue')['default']
    SettingsMenu: typeof import('./src/components/SettingsMenu.vue')['default']
    SettingsMenuPanel: typeof import('./src/components/SettingsMenuPanel.vue')['default']
    ThemeProvider: typeof import('./src/components/ThemeProvider.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
    Tool: typeof import('./src/components/Tool.vue')['default']
    ToolListCard: typeof import('./src/components/ToolListCard.vue')['default']
    ToolMenu: typeof import('./src/components/ToolMenu.vue')['default']
    ToolMenuControlsPanel: typeof import('./src/components/ToolMenuControlsPanel.vue')['default']
  }
}
