/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/colors': RouteRecordInfo<'/colors', '/colors', Record<never, never>, Record<never, never>>,
    '/dice': RouteRecordInfo<'/dice', '/dice', Record<never, never>, Record<never, never>>,
    '/patterns': RouteRecordInfo<'/patterns', '/patterns', Record<never, never>, Record<never, never>>,
    '/rand': RouteRecordInfo<'/rand', '/rand', Record<never, never>, Record<never, never>>,
    '/same': RouteRecordInfo<'/same', '/same', Record<never, never>, Record<never, never>>,
    '/tictactoe': RouteRecordInfo<'/tictactoe', '/tictactoe', Record<never, never>, Record<never, never>>,
    '/typing': RouteRecordInfo<'/typing', '/typing', Record<never, never>, Record<never, never>>,
  }
}
